# Generated by Django 4.2.7 on 2023-11-23 07:40

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_type', models.CharField(choices=[(1, 'Admin'), (2, 'Staff'), (3, 'Doctor'), (4, 'Nurse'), (5, 'Lap'), (6, 'Pharmacy'), (7, 'Physiotherapist'), (8, 'Patient')], default=8, max_length=2)),
                ('mobile', models.CharField(default='', max_length=15)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='DoctorCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('url_slug', models.CharField(max_length=200)),
                ('thumbnail', models.FileField(upload_to='')),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='ImageGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='LabDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('thumbnail', models.FileField(upload_to='')),
                ('description', models.TextField()),
                ('mobile_phone', models.CharField(max_length=15)),
                ('address', models.TextField(null=True)),
                ('open_time', models.TimeField(null=True)),
                ('close_time', models.TimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LabService',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('image', models.FileField(null=True, upload_to='')),
                ('details', models.TextField(null=True)),
                ('price', models.FloatField()),
                ('lap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lap_service', to='mobaderapp.labdetail')),
            ],
        ),
        migrations.CreateModel(
            name='MediaCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('video', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='NurseService',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('details', models.TextField(null=True)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('thumbnail', models.FileField(upload_to='')),
                ('description', models.TextField()),
                ('price', models.FloatField(default=0.0)),
                ('offer_type', models.CharField(default='offerdoctor', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PharmacyDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('thumbnail', models.FileField(upload_to='')),
                ('description', models.TextField()),
                ('mobile_phone', models.CharField(max_length=15)),
                ('address', models.TextField(null=True)),
                ('open_time', models.TimeField(null=True)),
                ('close_time', models.TimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PhysiotherapistService',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('details', models.TextField(null=True)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('thumbnail', models.FileField(upload_to='')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TeamSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='DoctorUser',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('profile_pic', models.FileField(default='', upload_to='')),
                ('price', models.FloatField(default=0.0)),
                ('address', models.CharField(default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_category', to='mobaderapp.doctorcategory')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('mobaderapp.customuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='LapUser',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('profile_pic', models.FileField(default='', upload_to='')),
                ('address', models.CharField(default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('mobaderapp.customuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='NurseUser',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('profile_pic', models.FileField(default='', upload_to='')),
                ('address', models.CharField(default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('mobaderapp.customuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='PatientUser',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('profile_pic', models.FileField(blank=True, default='', null=True, upload_to='')),
                ('address', models.CharField(default='', max_length=255)),
                ('verification', models.CharField(max_length=7)),
                ('confirmed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('mobaderapp.customuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='PharmacyUser',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('profile_pic', models.FileField(default='', upload_to='')),
                ('address', models.CharField(default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('mobaderapp.customuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='PhysiotherapistUser',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('profile_pic', models.FileField(default='', upload_to='')),
                ('address', models.CharField(default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('mobaderapp.customuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='StaffUser',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('profile_pic', models.FileField(default='', upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('mobaderapp.customuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='PhysiotherapistServiceTimes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('day', models.DateField()),
                ('start_time', models.TimeField(null=True)),
                ('end_time', models.TimeField(null=True)),
                ('active', models.BooleanField(default=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='physio_service_time', to='mobaderapp.physiotherapistservice')),
                ('physio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobaderapp.physiotherapistuser')),
            ],
            options={
                'ordering': ['-day'],
            },
        ),
        migrations.CreateModel(
            name='PharmacyMedicine',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('count', models.IntegerField(default=1)),
                ('image', models.FileField(null=True, upload_to='')),
                ('details', models.TextField(null=True)),
                ('price', models.FloatField()),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_medicine', to='mobaderapp.pharmacydetail')),
            ],
        ),
        migrations.CreateModel(
            name='OfferPhysioService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_physio', to='mobaderapp.offer')),
                ('physio_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='physio_service_offer', to='mobaderapp.physiotherapistservice')),
            ],
        ),
        migrations.CreateModel(
            name='OfferNurseService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nurse_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nurse_service_offer', to='mobaderapp.nurseservice')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_nurse', to='mobaderapp.offer')),
            ],
        ),
        migrations.CreateModel(
            name='OfferLabAnalytic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_analytic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_service_offer', to='mobaderapp.labservice')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_analytic', to='mobaderapp.offer')),
            ],
        ),
        migrations.CreateModel(
            name='NurseServiceTimes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('day', models.DateField()),
                ('start_time', models.TimeField(null=True)),
                ('end_time', models.TimeField(null=True)),
                ('active', models.BooleanField(default=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nurse_service_time', to='mobaderapp.nurseservice')),
                ('nurse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nurse_id_service', to='mobaderapp.nurseuser')),
            ],
            options={
                'ordering': ['-day'],
            },
        ),
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.FileField(default='', upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('auth_user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='physiotherapistservice',
            name='physiotherapist',
            field=models.ManyToManyField(to='mobaderapp.physiotherapistuser'),
        ),
        migrations.AddField(
            model_name='pharmacydetail',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_user', to='mobaderapp.pharmacyuser'),
        ),
        migrations.CreateModel(
            name='OfferOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_order', to='mobaderapp.offer')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_booking_order', to='mobaderapp.patientuser')),
            ],
        ),
        migrations.CreateModel(
            name='OfferDoctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_doctor', to='mobaderapp.offer')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_for_offer', to='mobaderapp.doctoruser')),
            ],
        ),
        migrations.AddField(
            model_name='nurseservice',
            name='nurse',
            field=models.ManyToManyField(to='mobaderapp.nurseuser'),
        ),
        migrations.AddField(
            model_name='labdetail',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lap_user', to='mobaderapp.lapuser'),
        ),
        migrations.CreateModel(
            name='DoctorTimes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('start_time', models.DateTimeField(null=True)),
                ('end_time', models.DateTimeField(null=True)),
                ('active', models.BooleanField(default=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_times', to='mobaderapp.doctoruser')),
            ],
        ),
        migrations.CreateModel(
            name='BookPhysio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, choices=[('PEN', 'Pending'), ('ACC', 'Accepted'), ('REF', 'Refused')], default='PEN', max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_service_physio', to='mobaderapp.physiotherapistservice')),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_time_physio_service', to='mobaderapp.physiotherapistservicetimes')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_physio', to='mobaderapp.patientuser')),
                ('physio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='physio_info', to='mobaderapp.physiotherapistuser')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookNurse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, choices=[('PEN', 'Pending'), ('ACC', 'Accepted'), ('REF', 'Refused')], default='PEN', max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_service_nurse', to='mobaderapp.nurseservice')),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_time_nurse_service', to='mobaderapp.nurseservicetimes')),
                ('nurse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nurse_info', to='mobaderapp.nurseuser')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_nurse', to='mobaderapp.patientuser')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookMedicine',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('count', models.IntegerField(default=1)),
                ('status', models.CharField(blank=True, choices=[('PEN', 'Pending'), ('ACC', 'Accepted'), ('REF', 'Refused')], default='PEN', max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_medicine_pharma', to='mobaderapp.pharmacymedicine')),
                ('pharma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pharma_info', to='mobaderapp.pharmacydetail')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_medicine', to='mobaderapp.patientuser')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookDoctor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_paid', models.BooleanField(default=False)),
                ('book_type', models.CharField(blank=True, choices=[('VISIT', 'Visit'), ('MEET', 'Meet')], default='VISIT', max_length=20)),
                ('meeting_room', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(blank=True, choices=[('PEN', 'Pending'), ('ACC', 'Accepted'), ('REF', 'Refused')], default='PEN', max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_time_doctor', to='mobaderapp.doctortimes')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_info', to='mobaderapp.doctoruser')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_doctor', to='mobaderapp.patientuser')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookAnalytic',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, choices=[('PEN', 'Pending'), ('ACC', 'Accepted'), ('REF', 'Refused')], default='PEN', max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_info', to='mobaderapp.labdetail')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_service_lab', to='mobaderapp.labservice')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_analytic', to='mobaderapp.patientuser')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
