# Generated by Django 4.2.6 on 2023-11-03 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobaderapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctortimes',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
