# Generated by Django 4.2.7 on 2023-11-23 12:55

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mobaderapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediacenter',
            name='video',
            field=embed_video.fields.EmbedVideoField(),
        ),
    ]
