# Generated by Django 4.2.6 on 2023-11-03 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobaderapp', '0002_doctortimes_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookdoctor',
            options={'ordering': ['-created_at']},
        ),
    ]
