# Generated by Django 4.2.6 on 2023-11-06 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobaderapp', '0003_alter_bookdoctor_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nurseservice',
            name='day',
            field=models.DateField(),
        ),
    ]
