# Generated by Django 4.2.6 on 2023-11-06 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobaderapp', '0004_alter_nurseservice_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='nurseservice',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
