# Generated by Django 4.2.6 on 2023-11-06 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mobaderapp', '0006_remove_nurseservice_active_remove_nurseservice_day_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='physiotherapistservice',
            name='day',
        ),
        migrations.RemoveField(
            model_name='physiotherapistservice',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='physiotherapistservice',
            name='start_time',
        ),
        migrations.CreateModel(
            name='PhysiotherapistServiceTimes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('day', models.DateField()),
                ('start_time', models.TimeField(null=True)),
                ('end_time', models.TimeField(null=True)),
                ('active', models.BooleanField(default=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='physio_service_time', to='mobaderapp.physiotherapistservice')),
            ],
            options={
                'ordering': ['-day'],
            },
        ),
    ]
