# Generated by Django 4.2.6 on 2023-11-06 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobaderapp', '0007_remove_physiotherapistservice_day_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='labservice',
            old_name='service_name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='labdetail',
            name='day_rest',
        ),
        migrations.RemoveField(
            model_name='labdetail',
            name='url_slug',
        ),
    ]
