# Generated by Django 4.2.6 on 2023-11-07 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mobaderapp', '0008_rename_service_name_labservice_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookNurse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, choices=[('PEN', 'Pending'), ('ACC', 'Accepted'), ('REF', 'Refused')], default='PEN', max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('nurse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nurse_info', to='mobaderapp.nurseuser')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_nurse', to='mobaderapp.patientuser')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_service_nurse', to='mobaderapp.nurseservice')),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_time_nurse_service', to='mobaderapp.nurseservicetimes')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
