# Generated by Django 4.2.6 on 2023-11-07 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mobaderapp', '0010_bookphysio'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookAnalytic',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, choices=[('PEN', 'Pending'), ('ACC', 'Accepted'), ('REF', 'Refused')], default='PEN', max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_info', to='mobaderapp.labdetail')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_analytic', to='mobaderapp.patientuser')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_service_lab', to='mobaderapp.labservice')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
