# Generated by Django 4.2.6 on 2023-11-08 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobaderapp', '0011_bookanalytic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pharmacymedicine',
            old_name='medicine_name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='pharmacydetail',
            name='day_rest',
        ),
        migrations.RemoveField(
            model_name='pharmacydetail',
            name='url_slug',
        ),
        migrations.AddField(
            model_name='pharmacymedicine',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
