# Generated by Django 4.2.6 on 2023-11-08 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mobaderapp', '0012_rename_medicine_name_pharmacymedicine_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookMedicine',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('count', models.IntegerField(default=1)),
                ('status', models.CharField(blank=True, choices=[('PEN', 'Pending'), ('ACC', 'Accepted'), ('REF', 'Refused')], default='PEN', max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_medicine_pharma', to='mobaderapp.pharmacymedicine')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_medicine', to='mobaderapp.patientuser')),
                ('pharma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pharma_info', to='mobaderapp.pharmacydetail')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
