# Generated by Django 4.2.6 on 2023-11-09 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobaderapp', '0013_bookmedicine'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientuser',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patientuser',
            name='verification',
            field=models.IntegerField(default=0),
        ),
    ]
