# Generated by Django 4.2.6 on 2023-11-09 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobaderapp', '0014_patientuser_confirmed_patientuser_verification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('thumbnail', models.FileField(upload_to='')),
                ('description', models.TextField()),
            ],
        ),
    ]
