# Generated by Django 4.2.6 on 2023-11-09 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobaderapp', '0015_slider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientuser',
            name='verification',
            field=models.CharField(max_length=7),
        ),
    ]
