# Generated by Django 4.2.6 on 2023-11-09 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobaderapp', '0016_alter_patientuser_verification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientuser',
            name='mobile',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
