# Generated by Django 4.2.7 on 2023-11-12 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobaderapp', '0017_alter_patientuser_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientuser',
            name='profile_pic',
            field=models.ImageField(default='profile.jpg', upload_to='profile_pics/'),
        ),
    ]
