# Generated by Django 3.1.7 on 2023-11-14 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobaderapp', '0025_auto_20231114_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientuser',
            name='profile_pic',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
