# Generated by Django 4.2.7 on 2023-11-18 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mobaderapp', '0030_alter_bookdoctor_book_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='MediaCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('video', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('thumbnail', models.FileField(upload_to='')),
                ('description', models.TextField()),
                ('price', models.FloatField(default=0.0)),
                ('offer_type', models.CharField(default='offerdoctor', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TeamSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='OfferPhysioService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_physio', to='mobaderapp.offer')),
                ('physio_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='physio_service_offer', to='mobaderapp.physiotherapistservice')),
            ],
        ),
        migrations.CreateModel(
            name='OfferOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_order', to='mobaderapp.offer')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_booking_order', to='mobaderapp.patientuser')),
            ],
        ),
        migrations.CreateModel(
            name='OfferNurseService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nurse_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nurse_service_offer', to='mobaderapp.nurseservice')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_nurse', to='mobaderapp.offer')),
            ],
        ),
        migrations.CreateModel(
            name='OfferLabAnalytic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_analytic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_service_offer', to='mobaderapp.labservice')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_analytic', to='mobaderapp.offer')),
            ],
        ),
        migrations.CreateModel(
            name='OfferDoctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_for_offer', to='mobaderapp.doctoruser')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_doctor', to='mobaderapp.offer')),
            ],
        ),
    ]
