# Generated by Django 4.2.7 on 2023-11-18 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobaderapp', '0033_alter_patientuser_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientuser',
            name='profile_pic',
            field=models.FileField(blank=True, default='', null=True, upload_to=''),
        ),
    ]
